// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timesTwo
int timesTwo(int x);
RcppExport SEXP fbroc_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    __result = Rcpp::wrap(timesTwo(x));
    return __result;
END_RCPP
}
// tpr_fpr_delta
IntegerVector tpr_fpr_delta(NumericVector pred, IntegerVector true_class, NumericVector thres);
RcppExport SEXP fbroc_tpr_fpr_delta(SEXP predSEXP, SEXP true_classSEXP, SEXP thresSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type true_class(true_classSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thres(thresSEXP);
    __result = Rcpp::wrap(tpr_fpr_delta(pred, true_class, thres));
    return __result;
END_RCPP
}
// tpr_fpr
NumericVector tpr_fpr(NumericVector pred, IntegerVector true_class, NumericVector thres);
RcppExport SEXP fbroc_tpr_fpr(SEXP predSEXP, SEXP true_classSEXP, SEXP thresSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type true_class(true_classSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type thres(thresSEXP);
    __result = Rcpp::wrap(tpr_fpr(pred, true_class, thres));
    return __result;
END_RCPP
}
