# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_auc <- function(tpr_fpr) {
    .Call('fbroc_get_auc', PACKAGE = 'fbroc', tpr_fpr)
}

get_roc_perf <- function(tpr_fpr, measure) {
    .Call('fbroc_get_roc_perf', PACKAGE = 'fbroc', tpr_fpr, measure)
}

get_roc_perf_uncached <- function(pred, true_class, thres, measure, n_boot) {
    .Call('fbroc_get_roc_perf_uncached', PACKAGE = 'fbroc', pred, true_class, thres, measure, n_boot)
}

tpr_fpr_boot_iterate <- function(n_thres, tpr_fpr_index, pos_index, neg_index) {
    .Call('fbroc_tpr_fpr_boot_iterate', PACKAGE = 'fbroc', n_thres, tpr_fpr_index, pos_index, neg_index)
}

true_tpr_fpr <- function(pred, true_class, thres) {
    .Call('fbroc_true_tpr_fpr', PACKAGE = 'fbroc', pred, true_class, thres)
}

find_thresholds <- function(pred, true_class) {
    .Call('fbroc_find_thresholds', PACKAGE = 'fbroc', pred, true_class)
}

tpr_fpr_boot <- function(pred, true_class, thres, n_boot) {
    .Call('fbroc_tpr_fpr_boot', PACKAGE = 'fbroc', pred, true_class, thres, n_boot)
}

get_tpr_matrix <- function(tpr_fpr, n_steps) {
    .Call('fbroc_get_tpr_matrix', PACKAGE = 'fbroc', tpr_fpr, n_steps)
}

