# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' generate
#'
#' @export
get_tpr_fpr_index <- function(pred, true_class, thres) {
    .Call('fbroc_get_tpr_fpr_index', PACKAGE = 'fbroc', pred, true_class, thres)
}

#' ok
#' @export
true_tpr_fpr <- function(pred, true_class, thres) {
    .Call('fbroc_true_tpr_fpr', PACKAGE = 'fbroc', pred, true_class, thres)
}

#' ok
#' @export
tpr_fpr_boot <- function(pred, true_class, thres, n_boot) {
    .Call('fbroc_tpr_fpr_boot', PACKAGE = 'fbroc', pred, true_class, thres, n_boot)
}

#' @export
get_auc <- function(tpr_fpr) {
    .Call('fbroc_get_auc', PACKAGE = 'fbroc', tpr_fpr)
}

#' @export
get_tpr_matrix <- function(tpr_fpr, n_steps) {
    .Call('fbroc_get_tpr_matrix', PACKAGE = 'fbroc', tpr_fpr, n_steps)
}

#' @export
find_thresholds <- function(pred, true_class) {
    .Call('fbroc_find_thresholds', PACKAGE = 'fbroc', pred, true_class)
}

