# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_roc_points <- function(tpr, fpr) {
    .Call('fbroc_add_roc_points', PACKAGE = 'fbroc', tpr, fpr)
}

roc_analysis <- function(pred, true_class) {
    .Call('fbroc_roc_analysis', PACKAGE = 'fbroc', pred, true_class)
}

paired_roc_analysis <- function(pred1, pred2, true_class) {
    .Call('fbroc_paired_roc_analysis', PACKAGE = 'fbroc', pred1, pred2, true_class)
}

get_uncached_perf_paired <- function(pred1, pred2, true_class, param, n_boot, measure) {
    .Call('fbroc_get_uncached_perf_paired', PACKAGE = 'fbroc', pred1, pred2, true_class, param, n_boot, measure)
}

tpr_fpr_boot2 <- function(pred, true_class, n_boot) {
    .Call('fbroc_tpr_fpr_boot2', PACKAGE = 'fbroc', pred, true_class, n_boot)
}

get_uncached_perf <- function(pred, true_class, param, n_boot, measure) {
    .Call('fbroc_get_uncached_perf', PACKAGE = 'fbroc', pred, true_class, param, n_boot, measure)
}

get_cached_perf <- function(tpr, fpr, param, measure) {
    .Call('fbroc_get_cached_perf', PACKAGE = 'fbroc', tpr, fpr, param, measure)
}

tpr_at_fpr_uncached <- function(pred, true_class, n_boot, n_steps) {
    .Call('fbroc_tpr_at_fpr_uncached', PACKAGE = 'fbroc', pred, true_class, n_boot, n_steps)
}

tpr_at_fpr_cached <- function(tpr, fpr, n_thres, n_steps) {
    .Call('fbroc_tpr_at_fpr_cached', PACKAGE = 'fbroc', tpr, fpr, n_thres, n_steps)
}

